### ISSUE TITLE
Circle is vanishing?

### ISSUE THREAD

**Issue by ghost** [QuantumZain/chaotic-system#3]
i wanted to insert a circle. but whenever i insert it, it disappears immediately. i don't think it's a problem with the code. i probably just don't understand it properly. could you help me?

**Comment by QuantumZain** [comment]
Hi @Donniii, thanks for finding my code and using it ;) I wrote this so long and forgot about it.

Anyways, about your issue, could you show a snippet of your code so I can see exactly where the problem is? I guess the issue may be that you're defining the coordinates of the balls outside of the window, try using the existing ball's coordinates as reference.

In the meantime here are a few more examples that should work, you can find these from the code too by uncommenting them. 
```
greenball = Balls("green ball", algeablue, 8, 0, width//2+bigr-20, height//2-50, "golf_ball.wav")
yellowball = Balls("green ball", magenta2, 8, 0, width//3, height//2,"trm.wav")
blueball = Balls("green ball", blue, 8, 0, width*2//3+5, height//2, "trm.wav")
```
okay now i have to go back to study for my semiconductors final :(

**Comment by ghost** [comment]
Thanks for your response! This realy helped me
